### ISSUE TITLE
Ambi-light left and right effect

### ISSUE THREAD

**Issue by Tristimdorion** [zim514/script.service.hue#147]
Instead of one generic ambi-light color for all assigned lights, it would be nice to have the left and right screen edges used for the color calculation and the ability to assign a color to that light based on the screen edge average color, creating a more immersive feel when using two lights at either side of the tv.

This would more closely resemble the implementation used in the Philips TV's or the need for the HDMI Sync Box.

**Comment by zim514** [comment]
It's something I've considered but unfortunately don't have time to implement myself. If someone volunteers a PR to accomplish this I'd probably merge it.

**Comment by rgnjwrgjlnrb** [comment]
The Kodi add-on "script.kodi.hue.ambilight" is able to do it, but it seems to be abandoned and doesn't work in the latest versions due to unmet python dependencies. Maybe the relevant code could be merged/integrated into this add-on since it's already implemented?

https://github.com/mpolednik/script.kodi.hue.ambilight

**Comment by tommargar** [comment]
The addon mentioned was updated on a fork and can be found here https://github.com/dolorosus/script.kodi.hue.ambilight
Found no feature for separating the colors, on my 3 Hue Play lights it goes nuts.
