### ISSUE TITLE
RenderCapture doesn't work for some 4K content

### ISSUE THREAD

**Issue by zim514** [zim514/script.service.hue#19]
Not all 4K content, could be HDR or H265 only. Needs to be investigated

**Comment by neothematrix** [comment]
hi, I haven't had time to test this, but if it's anything similar to mpolednik plugin issue (https://github.com/mpolednik/script.kodi.hue.ambilight/issues/82), it's very likely this affects any content using "MediaCodec Surface" hardware acceleration. This is usually "worked around" by disabling hardware acceleration in Kodi (MediaCodec Surface or whatever is in use on the device), of course this means many streams will stutter because the device is not powerful enough to decode 4k/h265 without hw acceleration.

**Comment by zim514** [comment]
is that an android thing? VAAPI hardware acceleration on windows and linux seems to work just fine

**Comment by neothematrix** [comment]
yeah I think it's mostly media players using Android (Android TV, generic android boxes, Amazon Fire TV, ...)

**Comment by zim514** [comment]
Alright, nothing I can do about that. Thanks for letting me know and pointing me to that issue. Looks like that SPMC fork has a solution for those that really need it.
