### ISSUE TITLE
Hue Service is sometimes not started together with Kodi

### ISSUE THREAD

**Issue by szotsaki** [zim514/script.service.hue#288]
**Describe the bug**

Sometimes, not always, this service is not found in the "running" list of Kodi extensions. It also means that Hue control doesn't work, even if when the extension is configured properly.

If I go to its extension page, disable and re-enable it, Hue control got restored (and the extensions is shown as running in Kodi).

**Expected behavior**
Extension starts automatically with Kodi every time.

It is possible that Kodi was shut down in an uncontrolled manner (e.g. Android killed it for some reason).

**System (please complete the following information):**
 - OS: SHIELD
 - Kodi Version: 21

**Comment by SamDW96** [comment]
I have the same issue, generally when the SHIELD is hibernating with Kodi still opened. Turning it back on from there will have Kodi still open, but the Hue service stopped. 

Sometimes this also happens when Kodi is still running in the background, and reopened later. When Kodi was purged from memory by Android, and Kodi starts from scratch again, there is no issue. It only happens when Kodi doesn't have a 'fresh' restart.

**Comment by zim514** [comment]
If this is still occuring on the latest 2.0+ versions, please provide debug logs.
