### ISSUE TITLE
Slightly confused by feature list

### ISSUE THREAD

**Issue by Thomas-O** [zim514/script.service.hue#33]
Sorry if I'm a bit dim, but can the add-on do these basics with white lights?:

1. 0% on playback
2. 50% on pause
3. 100% on stop

I'm sure that many people will greatly appreciate the fancy options and ambilight features, but I only need 1-3. And I'll need to both invest in a hub upgrade (from v1 to v2) and upgrade my LibreElec from Krypton to Leia before installing your add-on. It'd be nice to know that it'll be worth the time and expense.

While I'm here, at present I'm using Martin Polednik's Kodi Philips Hue add-on with my LE box. While it works just fine it unfortunately can't differentiate between video types. Dimming to 0% is fine for Movies and TV Shows, but not so great for Live TV: I'd really rather not have to sit in the dark every time I want to catch up on the news. Which is why I was wondering if you could provide an option to define separate actions for each video type. Or just for Live TV.

Thanks for the help.

**Comment by zim514** [comment]
Hi

It will activate any scene you want on playback, pause or stop. Rather than
setup a percentage or something in the plugin, you can setup your lights in
the Hue app and then save it. If Hue lets you create a scene for it, this
script will just activate the same scene.

As for the video types, the options aren't as granular as you describe, but
you can disable it for Live TV, it falls under the "other video" category
along with disks. For now I'm not planning on adding any more options. The
settings UI isn't great and as you pointed out there are too many features
making it more complex than I originally intended :)
