### ISSUE TITLE
Feature request: Disable Hue Labs effects while playing with Ambilight enabled

### ISSUE THREAD

**Issue by toupeira** [zim514/script.service.hue#77]
I usually have Colorloop from Hue Labs enabled on my living room lights, and noticed some "bleed through" when the Ambilight color in Kodi stays the same/similar for a while, and Colorloop will fade to different colors in the background.

After some googling I learned that Hue Labs effects set up a dummy sensor on the bridge, and this can be used to enable and disable the effect.

I hacked this into the addon with the following patch to `resources/lib/AmbiGroup.py`:

```diff
@@ -48,6 +48,9 @@
         if self.isPlayingVideo():
             if self.enabled and self.checkActiveTime() and self.checkVideoActivation(self.videoInfoTag):
 
+                # disable colorloop
+                self.bridge.sensors[70].state(status=0)
+
                 if self.forceOn:
                     self._force_on(self.ambiLights, self.bridge, self.savedLightStates)
 
@@ -95,6 +98,9 @@
                 logger.error("onPlaybackStopped: Hue call fail: {}".format(exc))
                 reporting.process_error(exc)
 
+        # enable colorloop
+        self.bridge.sensors[70].state(status=1)
+
     def loadSettings(self):
         logger.debug("AmbiGroup Load settings")
```

Would you accept a PR to add this? The `70` here is the ID of the sensor for the Colorloop "instance" of my living room, so this would need to be configurable. I'm new to Kodi addon development but would be happy to give this a go.

I could also easily script this when launching/quitting Kodi, but I'd rather only toggle the effect during actual video playback. I also looked for generic "callback" addons which let you execute custom commands on events, but couldn't find anything supported on Kodi 19.

**Comment by zim514** [comment]
Hi! 

Thanks for offering to contribute. I would accept a PR for this. I think instead of making the user figure out the ID, you could loop through all the sensors and look for those that have modelid:"HUELABSENUM", and turn them all off. I think this would be a lot easier than trying to create a sensor loop/selection UI.  

That said, if you want to let the user select one or multiple sensors to turn off, you could use a similar approach to the 'Select Scene Button. That logic is in core.py, look for "command == sceneSelect"

I agree that it would be better to do it on playback start/stop. You can find the logic for this in KodiGroup.py and AmbiGroup.py. There are methods called onAVStarted, onPlayBackStopped, onPlayBackPaused, which are called by Kodi when the video player does either of those actions. 

You could also turn the labs back on, but doing it for only those that were turned off in the first place would be more work. 

I don't really have the time to develop this myself, but if you do want to take this on, I'm happy to help point you to documentation, examples, etc

**Comment by zim514** [comment]
Implemented
